language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - travis_wait 30 npm run test
  - travis_wait 30 npm run build
  #- npm run test:prod && npm run build
after_success:
  - travis_wait 30 npm run report-coverage
  - travis_wait 30 npm run deploy-docs
  - travis_wait 30 npm run semantic-release
